---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(dummies)
library(MASS)
```


```{r}
stage_data <- read_csv("C:/Users/Tuna/Desktop/Statistical Learning/2020-04-07/stage_data.csv")
tdf_stages <- read_csv("C:/Users/Tuna/Desktop/Statistical Learning/2020-04-07/tdf_stages.csv")
tdf_winners <- read_csv("C:/Users/Tuna/Desktop/Statistical Learning/2020-04-07/tdf_winners.csv")
```
```{r}
tdf_totals <- merge(stage_data,tdf_winners,by=c("edition"))
tdf_totals
```
```{r}
tdf_totals <- merge(tdf_totals, tdf_stages, by=c("stage","year"))
tdf_totals
```
```{r}
sapply(tdf_totals,function(x) length(unique(x)))
```
```{r}
tdf_totals <- tdf_totals %>%
  rename(
    rider_age = age.x,
    winner_age = age.y,
    winner_distance = distance.x,
    stage_distance = distance.y
  )
tdf_totals
```
```{r}
tdf_totals <- read_csv("C:/Users/Tuna/Desktop/Statistical Learning/tdf_totals.csv")
```


```{r}
ggplot(tdf_totals, aes(x=year, y=winner_distance)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y= "Total Distance", title = "Distance over the Years")
```
```{r}
ggplot(tdf_totals, aes(x=year, y=rider_age)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y= "Rider Age", title = "Average Ages Competing across Years")
```
```{r}
ggplot(tdf_totals, aes(x=year, y=time_overall)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y= "Overall Time", title = "Overall Time changes across Years")
```
```{r}
km_hour <- (tdf_totals$winner_distance / tdf_totals$time_overall)
ggplot(tdf_totals, aes(x=year, y=km_hour)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y= "Km/H")
```
```{r}
ggplot(tdf_totals, aes(x=year, y=stage)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y= "Stages", title = "Number of Stages per Year")
```
```{r}
ggplot(tdf_totals) +
  geom_point(aes(x= year, y = winner_distance), color = "red") +
  geom_point(data = tdf_totals, aes(x = year, y = km_hour*100), color = "blue") +
  scale_y_continuous(sec.axis = sec_axis(~./100, name = "km/h")) +
  labs(x = "Year", y = "Distance", title = "Distance and Speed over the Years") +
  theme(axis.title.y.right = element_text(color = "blue"), axis.title.y = element_text(color = "red"))

```
```{r}
ggplot(tdf_stages, aes(x = year, y = distance)) +
  geom_point(aes(color = type))
```

```{r}
ggplot(tdf_totals, aes(x=year, y=time_margin)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y= "Time Margin")
  
```


```{r}
tdf_winners$nationality <- fct_infreq(tdf_winners$nationality)
ggplot(tdf_winners) +
  geom_bar(aes(x = nationality)) +
  labs(x = "Nationality", y = "Number of overall wins", title = "TDF wins per country") + 
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
tdf_stages$winner_country <- fct_infreq(tdf_stages$winner_country)
tdf_stages %>%
#arrange(desc(winner_country)) %>%
ggplot(na.rm=TRUE) +
  geom_bar(aes(x = winner_country, color = type, fill = type)) +
  labs(x = "Country", y = "Number of Wins", title = "Stage Wins per Country by Stage Type") +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
tdf_stages$winner_country <- fct_infreq(tdf_stages$winner_country)
tdf_stages %>%
#arrange(desc(winner_country)) %>%
ggplot(na.rm=TRUE) +
  geom_bar(position="fill", aes(x = winner_country, color = type, fill = type)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country", y = "Proportion", title = "Proportional look at Country wins per stage type")
```
```{r}
tdf_stages$winner_country <- fct_infreq(tdf_stages$winner_country)
tdf_stages %>%
  filter(winner_country %in% c("FRA", "BEL", "ITA", "NED", "ESP")) %>%
ggplot(na.rm=TRUE) +
  geom_bar(position="fill", aes(x = winner_country, color = type, fill = type)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country", y = "Proportion of Wins", title = "Top 5 Countries with Stage Wins")
```

```{r}
tdf_totals$type = fct_infreq(tdf_totals$type)
ggplot(tdf_totals, aes(fill = type)) +
  geom_point(aes(x = year, y = type, color = type)) +
  labs(x = "Year", y = "Stage Type", title = "Stage Types across Years")
```
```{r}
glimpse(tdf_stages)
```
```{r}

tdf_france <- filter(tdf_stages, country_code == 3)
fit <- lm(country_code ~ flat_cobblestone + flat + half + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time + plain + plain_with_cobble + stage_with_mountain + team_time_trial + transition + distance, data = tdf_france)
step <- stepAIC(fit, direction="both")
step$anova
```
```{r}
tdf_france <- filter(tdf_stages, country_code == 11)
fit2 <- lm(country_code ~ flat_cobblestone + flat + half + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time + plain + plain_with_cobble + stage_with_mountain + team_time_trial + transition + distance, data = tdf_france)
step <- stepAIC(fit2, direction="both")
step$anova
```
```{r}
fit2
```
```{r}
groupcountry <- tdf_stages %>%
  group_by(type) %>% 
  count(winner_country, sort = T) %>% 
  mutate(winner_country = reorder(winner_country, n),
         winner_country=as.character(winner_country)) %>% 
  filter(winner_country!='na') 
groupcountry
```


```{r}
groupcountry %>%
  filter(winner_country %in% c("FRA", "BEL", "ESP", "ITA", "USA")) %>%
ggplot(aes(x = type ,y = n, fill = winner_country)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
groupcountry %>%
  filter(winner_country %in% c("FRA", "BEL", "ESP", "ITA", "NED") & type %in% c("Plain stage", "Stage with mountain", "Individual time trial", "Hilly stage", "Team time trial")) %>%
ggplot(aes(x = type ,y = n, fill = winner_country)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(y = "Amount of Stage Type", x = "Stage Type", title = "Top 5 Stage Types with Top Countries", legend = "Country")
```
```{r}
groupstage <- tdf_stages %>%
  group_by(winner_country) %>% 
  count(stage, sort = T) %>% 
  mutate(stage = reorder(stage, n),
         stage=as.character(stage)) %>% 
  filter(stage!='na') 
groupstage
```

```{r}

```

```{r}
groupstage %>%
  filter(winner_country %in% c("FRA", "BEL", "ESP", "ITA", "NED")) %>%
  group_by(stage) %>%
ggplot(aes(x=stage, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) + 
  labs(x = "Stage Number", y = "Number of Wins", title = "Country Wins by Stage Number")
```
```{r}
groupstage$stage <- as.numeric(as.character(groupstage$stage))
groupstage[order(groupstage$stage),]
```
```{r}
groupstage %>%
  filter(winner_country == "FRA") %>%
  group_by(stage) %>%
ggplot(aes(x=stage, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red") +
  labs(x = "Stage #", y = "Number of Wins", title = "France Wins per Stage") +
  theme(legend.position = "none")
```
```{r}
groupstage %>%
  filter(winner_country == "BEL") %>%
  group_by(stage) %>%
ggplot(aes(x=stage, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red") +
    labs(x = "Stage #", y = "Number of Wins", title = "Belgium Wins per Stage") +
  theme(legend.position = "none")
```
```{r}
groupstage %>%
  filter(winner_country == "ESP") %>%
  group_by(stage) %>%
ggplot(aes(x=stage, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red") + 
    labs(x = "Stage #", y = "Number of Wins", title = "Spain Wins per Stage") +
  theme(legend.position = "none")
```
```{r}
groupstage %>%
  filter(winner_country == "ITA") %>%
  group_by(stage) %>%
ggplot(aes(x=stage, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red") + 
    labs(x = "Stage #", y = "Number of Wins", title = "Italy Wins per Stage") +
  theme(legend.position = "none")
```
```{r}
groupstage %>%
  filter(winner_country == "NED") %>%
  group_by(stage) %>%
ggplot(aes(x=stage, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red") + 
    labs(x = "Stage #", y = "Number of Wins", title = "Netherlands Wins per Stage") +
  theme(legend.position = "none")
```

```{r}
groupcountry2 <- tdf_stages %>%
  group_by(year) %>% 
  count(winner_country, sort = T) %>% 
  mutate(winner_country = reorder(winner_country, n),
         winner_country=as.character(winner_country)) %>% 
  filter(winner_country!='na') 
groupcountry
```
```{r}
groupcountry2 %>%
  filter(winner_country %in% c("FRA", "BEL", "ESP", "ITA", "USA")) %>%
ggplot(aes(x=year, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE)
```
```{r}
class(tdf_stages$stage)
x <- type.convert(tdf_stages$stage)
class(x)
```
```{r}
arrange(tdf_stages$stage_2)
```
```{r}
groupcountry2 %>%
  filter(winner_country == "FRA") %>%
  ggplot(aes(x=year, y=n, color = winner_country)) +
  geom_point() +
  geom_smooth(method=lm, color="red", fill="red", se=TRUE) +
  labs(x = "Year", y = "Number of Wins", title = "France Wins per Year") +
  theme(legend.position = "none")
```
```{r}
write_csv(groupcountry,path = "C:/Users/Tuna/Desktop/Statistical Learning/groupcountry.csv")
```

```{r}
countrystagewins <- read.csv("C:/Users/Tuna/Desktop/Statistical Learning/countrystagewins.csv")
```

```{r}
filteredwins <- filter(countrystagewins, winner_country == "FRA")
lm(wins ~ stage + flat_cobble + flat + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time_trial + plain + plain_with_cobble + stage_with_mountain + team_time_trial + transition, data = filteredwins)
```
```{r}
filteredwins <- filter(countrystagewins, winner_country == "BEL")
lm(wins ~ stage + flat_cobble + flat + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time_trial + plain + plain_with_cobble + stage_with_mountain + team_time_trial + transition, data = filteredwins)
```
```{r}
filteredwins <- filter(countrystagewins, winner_country == "ITA")
lm(wins ~ stage + flat_cobble + flat + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time_trial + plain + plain_with_cobble + stage_with_mountain + team_time_trial + transition, data = filteredwins)
```
```{r}
filteredwins <- filter(countrystagewins, winner_country == "NED")
lm(wins ~ stage + flat_cobble + flat + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time_trial + plain + plain_with_cobble + stage_with_mountain + team_time_trial + transition, data = filteredwins)
```
```{r}
filteredwins <- filter(countrystagewins, winner_country == "ESP")
lm(wins ~ stage + flat_cobble + flat + high_mountain + hilly + individual_time_trial + intermediate + medium_mountain + mountain + mountain_time_trial + plain + plain_with_cobble + stage_with_mountain, data = filteredwins)
```
```{r}
filteredwins <- filter(countrystagewins, winner_country == "ESP")
glm(wins ~ stage + type, data = filteredwins)
```
```{r}
countrystagewins %>%
  filter(winner_country == "FRA" & type == "Plain stage") %>%
  ggplot(aes(x = stage, y = wins, color = type)) +
  geom_point()
```

